apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: qcon-api
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "qcon-api-kubeauthbot-web"
        vault.hashicorp.com/agent-inject-secret-config: "web-apps/data/qcon-api"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "web-apps/data/qcon-api" -}}
          ADMIN_USERNAME="{{ .Data.data.ADMIN_USERNAME }}"
          ADMIN_PASSWORD="{{ .Data.data.ADMIN_PASSWORD }}"
          API_KEY="{{ .Data.data.API_KEY }}"
          DJANGO_SECRET_KEY="{{ .Data.data.DJANGO_SECRET_KEY }}"
          POSTGRES_PASSWORD="{{ .Data.data.POSTGRES_PASSWORD }}"
          ELASTIC_APM_SECRET_TOKEN="{{ .Data.data.ELASTIC_APM_SECRET_TOKEN }}"
          {{- end }}
    spec:
      containers:
        - name: nginx
          envFrom:
          - configMapRef:
              name: elasticapm-config
        - name: qcon-api
          envFrom:
          - configMapRef:
              name: elasticapm-config
