apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
commonLabels:
  environment: web
commonAnnotations:
  version: 2.18.8 # {"$imagepolicy": "qcon:qcon-api-image-policy-web:tag"}
images:
  - name: "qcon-api"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-api"
    newTag: "2.18.8" # {"$imagepolicy": "qcon:qcon-api-image-policy-web:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-api-web
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
