# This file is for teaching kustomize how to substitute names in the HelmRelease CRD
#
nameReference:

- kind: VaultAuth
  fieldSpecs:
    - path: spec/vaultAuthRef
      kind: VaultStaticSecret

- kind: ServiceAccount
  fieldSpecs:
    - path: spec/kubernetes/serviceAccount
      kind: VaultAuth

- kind: VaultStaticSecret
  fieldSpecs:
    - path: spec/template/spec/containers/envFrom/secretRef/name
      kind: Deployment
