apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  method: kubernetes
  mount: kubernetes-review
  kubernetes:
    role: qcon-api-kubeauthbot-review
    serviceAccount: serviceaccount
    audiences:
      - vault
