kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: qcon-api
  namespace: fleet-default
spec:
  repo: https://issues.ltc.bcit.ca/web-apps/qcon/qcon-api
  branch: release
  defaultNamespace: qcon
  # For a private registry you must supply a clientSecretName. A default
  # secret can be set at the namespace level using the BundleRestriction
  # type. Secrets must be of the type "kubernetes.io/ssh-auth" or
  # "kubernetes.io/basic-auth". The secret is assumed to be in the
  # same namespace as the GitRepo
  #
  clientSecretName: dependabot-qcon-api
  #
  # Disable SSL verification for git repo
  #
  insecureSkipTLSVerify: false
  #
  paths:
  - deploy/overlays/prod

  # The service account that will be used to perform this deployment.
  # This is the name of the service account that exists in the
  # downstream cluster in the fleet-system namespace. It is assumed
  # this service account already exists so it should be create before
  # hand, most likely coming from another git repo registered with
  # the Fleet manager.
  #
  # serviceAccount: moreSecureAccountThanClusterAdmin

  # targets:
  # - name: prod
  #   clusterSelector:
  #     matchLabels:
  #       env: prod

  # targetCustomizations:
  # - name: dev
  #   clusterSelector:
  #     matchLabels:
  #       env: dev
  #   kustomize:
  #     dir: deploy/overlays/dev

  # kustomize:
  #   dir: ""