apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: qcon-api-ingress
spec:
  tls:
  - hosts:
      - qcon-api.ltc.bcit.ca
    secretName: star-ltc-bcit-ca
  rules:
  - host: qcon-api.ltc.bcit.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qcon-api-service
            port:
              number: 8000