namespace: qcon-api

resources:
  - ../../base
  - configmap.yaml

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

secretGenerator:
- name: star-ltc-bcit-ca
  files:
    - "tls.cert"
    - "tls.key"
  type: "kubernetes.io/tls"