apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qcon-api

resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml

patches:
  - path: deployment.yaml
    target:
      labelSelector: "env=prod"

secretGenerator:
- type: kubernetes.io/tls
  name: star-dev-ltc-bcit-ca
  files:
    - tls.crt
    - tls.key

generatorOptions:
  disableNameSuffixHash: true