namespace: qcon

resources:
  - ../../base
  - configmap.yaml
  - ingress.yaml

patchesStrategicMerge:
  - deployment.yaml

secretGenerator:
- type: kubernetes.io/tls
  name: star-ltc-bcit-ca
  files:
    - tls.crt
    - tls.key

generatorOptions:
  disableNameSuffixHash: true