apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: qcon-api
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443"
    spec:
      containers:
        - name: qcon-api
          env:
            - name: GIT_TAG
              value: 2.18.16-01cfaa65--2023-10-11.1697041352 # {"$imagepolicy": "qcon:qcon-api-image-policy-latest:tag"}
