apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: qcon-api
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443"
    spec:
      containers:
        - name: qcon-api
          env:
            - name: GIT_TAG
              value: 2.18.11-41cc30df--2023-09-26.1695767429 # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
