apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: qcon-api-
nameSuffix: -latest
# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 2.18.15-44d4722a--2023-09-27.1695830530 # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
images:
  - name: "qcon-api"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-api"
    newTag: "2.18.15-44d4722a--2023-09-27.1695830530" # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
# Patches ingress with "latest--" and deployment with annotations
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-api-latest
    behavior: merge
