apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
commonLabels:
  environment: latest
commonAnnotations:
  version: 2.18.9-1c0ba11b--2023-09-26.1695750369 # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
images:
  - name: "qcon-api"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-api"
    newTag: "2.18.9-1c0ba11b--2023-09-26.1695750369" # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-api-latest
    behavior: merge
components:
  - ./vault-secrets
