apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
# Resource names in a shared namespace must be unique
#
namePrefix: qcon-api-
commonLabels:
  environment: latest
commonAnnotations:
  version: 2.18.15-44d4722a--2023-09-27.1695830530 # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
images:
  - name: "qcon-api"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-api"
    newTag: "2.18.15-44d4722a--2023-09-27.1695830530" # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
# Patches ingress with "latest--" and deployment with annotations
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-api-latest
    behavior: merge
components:
  - ./vault-secrets
