apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcon-api
spec:
  template:
    spec:
      containers:
      - name: qcon-api
        image: qcon-api
        env:
        - name: DEBUG
          value: "True"