apiVersion: apps/v1
kind: Deployment

metadata:
  name: qcon-api
  labels:
    app: qcon-api
    env: dev
spec:
  template:
    spec:
      containers:
      - name: qcon-api
        image: qcon-api
        env:
        - name: DEBUG
          value: "True"
# Insecure defaults
        - name: ADMIN_USERNAME
          value: "admin"
        - name: ADMIN_PASSWORD
          value: "admin"
        - name: API_HTTP_ADDR
          value: https://qcon-api.dev.ltc.bcit.ca
        - name: API_KEY
          value: "2222222222222222222222222222222222222222"
        - name: DJANGO_SECRET_KEY
          value: "d8&z=vqy5b#lu0=an1xx9b_7n480af=-gdnqwqvtrs&d6el9=("