##### Pipeline Overview #####
#
# #### `main` branch ####
#
# - continuously deployed to k8s staging cluster
# - on all MR, build new image tagged "latest"
# - deploy image tagged `latest` to k8s staging cluster
#
# #### `release` branch ####
#
# - continuously deployed to k8s prod cluster
# - on all MR, build new GitLab release
# - git tag commit with semantic-release version
# - build new image tagged with semver version
# - build new image tagged with `stable`
# - deploy image tagged `stable` to k8s prod cluster (Fleet)
#
# #### Notes ####
#
# - builds performed by Kaniko (k8s prod cluster)
#   - Kaniko docs are here: https://github.com/GoogleContainerTools/kaniko
#   - GitLab CI/CD pipeline docs for Kaniko builds are here: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
# - semantic versioning is automated by analyzing commit messages for keywords
#   - refer to : https://semantic-release.gitbook.io/semantic-release/usage/configuration for CLI configuration

stages:
  - test
  - build
  - semver-tagging
  - release
  - deploy

# include:
#   - template: Security/SAST.gitlab-ci.yml
#   - template: Security/Secret-Detection.gitlab-ci.yml
#   - template: Security/License-Scanning.gitlab-ci.yml

variables:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"
  VAULT_SERVER_URL: "https://vault.ltc.bcit.ca:8200"
  VAULT_AUTH_ROLE: "read-tokens"
  PROJECT_REGISTRY: "registry.dev.ltc.bcit.ca"
  KUBERNETES_POD_ANNOTATIONS_1: "app.gitlab.com/env=$CI_ENVIRONMENT_SLUG"
  KUBERNETES_POD_ANNOTATIONS_2: "app.gitlab.com/app=$CI_PROJECT_PATH_SLUG"

# #### Re-usable configurations ####
#
# Kaniko template
.build_with_kaniko:
  stage: build
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]

# Deploy template
.deploy:
  stage: deploy
  image: bitnami/kubectl:latest

# debug_trace:
#   image: alpine
#   stage: deploy
#   environment:
#     name: staging
#     url: https://builds.dev.ltc.bcit.ca
#     kubernetes:
#       namespace: default
#   variables:
#     CI_DEBUG_TRACE: "true"
#   script:
#   - echo 'Testing debug trace'


# #### Jobs ####
#
# Run static application security test (https://issues.ltc.bcit.ca/help/user/application_security/sast/index)
security_scan:
  stage: test
  script:
    - echo "running scan"
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main" && $CI_MERGE_REQUEST_EVENT_TYPE != "detached"'

# This job is for building the image with Kaniko (latest)
.build_latest:
  extends: .build_with_kaniko
  # needs: ["security_scan"]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - "/kaniko/executor --context $CI_PROJECT_DIR $KANIKO_CACHE_ARGS
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:latest"
  # rules:
  #   - if: '$CI_COMMIT_REF_SLUG == "main" && $CI_MERGE_REQUEST_EVENT_TYPE != "detached"'

# This job deploys the image tagged with `latest` to the k8s staging cluster
deploy_review:
  extends: .deploy
  stage: deploy
  # needs: ["build_latest"]
  environment:
    name: staging
    url: https://staging.dev.ltc.bcit.ca/$CI_PROJECT_NAME
    kubernetes:
      namespace: $CI_PROJECT_NAME
    on_stop: stop_review
  # rules:
  #   - if: '$CI_COMMIT_REF_SLUG == "main" && $CI_MERGE_REQUEST_EVENT_TYPE != "detached"'
  #
  # Using external secrets: https://docs.gitlab.com/ee/ci/secrets/index.html
  #
  secrets:
    PROJECT_TOKEN_USERNAME:
      vault: dependabot-$CI_PROJECT_NAME/PROJECT_TOKEN_USERNAME@tokens
    PROJECT_TOKEN_PASSWORD:
      vault: dependabot-$CI_PROJECT_NAME/PROJECT_TOKEN_PASSWORD@tokens
  script:
    - echo "deploy to staging for review"
    - kubectl create ns $CI_PROJECT_NAME -o yaml --dry-run=client | kubectl apply -f -
    - "kubectl create secret docker-registry dependabot-$CI_PROJECT_NAME \
      --docker-server=$PROJECT_REGISTRY \
      --docker-username=$(cat $PROJECT_TOKEN_USERNAME) \
      --docker-password=$(cat $PROJECT_TOKEN_PASSWORD) \
      --docker-email=courseproduction@bcit.ca -o yaml --dry-run=client | kubectl apply -f -"
    - kubectl apply -k deploy/overlays/staging

#   - spin up and connect to Rancher staging cluster (need .kube/config for staging)
#   - pull latest image from GitLab registry (depenabot credentials from vault - deploy-tokens/dependabots/dependabot-web-apps)
#   - deploy the image using kustomize, injecting secrets from vault (vault path to app secrets)
# TODO: update overlays/staging/deployment.yaml to use pipeline variable ($CI_COMMIT_TAG) to pull appropriate image

# read_secrets:
#   stage: test
#   # Using external secrets: https://docs.gitlab.com/ee/ci/secrets/index.html
#   secrets:
#     DEPENDABOT_USERNAME:
#       vault: web-apps/dependabot-web-apps/CI_DEPLOY_USERNAME@tokens
#     DEPENDABOT_PASSWORD:
#       vault: web-apps/dependabot-web-apps/CI_DEPLOY_PASSWORD@tokens
#   script:
#     - cat $DEPENDABOT_USERNAME

stop_review:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "Remove review app"
    - kubectl delete -k deploy/overlays/staging
  environment:
    name: staging
    kubernetes:
      namespace: $CI_PROJECT_NAME
    action: stop
  when: manual

# This job is for running semantic-versioning for releasing whenever there is a merge request
# on the release branch
semver_release:
  image: node:12-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - export GIT_AUTHOR_NAME=$GITLAB_USER_LOGIN
    - export GIT_AUTHOR_EMAIL=$GITLAB_USER_EMAIL
    - export GIT_COMMITTER_NAME=$GITLAB_USER_LOGIN
    - export GIT_COMMITTER_EMAIL=$GITLAB_USER_EMAIL
    - npm install -g semantic-release @semantic-release/gitlab
  secrets:
    GITLAB_TOKEN:
      vault: dependabot-$CI_PROJECT_NAME/GITLAB_TOKEN@tokens
  script:
    - semantic-release
      --branches release
      --repository-url $CI_PROJECT_URL
      --plugins '@semantic-release/commit-analyzer, @semantic-release/release-notes-generator, @semantic-release/gitlab'
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "release" && $CI_MERGE_REQUEST_EVENT_TYPE != "detached"'

# This job is for building the image with Kaniko (stable)
build_stable:
  extends: .build_with_kaniko
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json  
    - "/kaniko/executor --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_TAG 
      --destination $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:stable"
  rules:
     - if: '$CI_COMMIT_TAG'

# This job deploys the most recent `stable` image to the k8s prod cluster
deploy_production:
  extends: .deploy
  needs: ["build_stable"]
  environment: production
  rules:
    - if: $CI_COMMIT_TAG
  script:
      - echo "deploy to prod"
# TODO: Get Fleet to pickup changes