version: "3"

services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - db-volume:/var/lib/postgres
  #   networks:
  #     - app-network
  #   ports:
  #     - "5432:5432"
  app:
    build: .
    # command: python manage.py runserver 0.0.0.0:9000
#    image: qcon
    restart: always
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    working_dir: /code
    networks:
      - app-network

# volumes:
#   db-volume: 

networks:
  app-network:
    driver: bridge