version: "3"

services:
  postgres:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    networks:
      qcon-network:

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: qcon-api
    environment:
      - 'DEBUG=True'
      - 'ADMIN_USERNAME=admin'
      - 'ADMIN_PASSWORD=admin'
      - 'POSTGRES_PASSWORD=postgres'
      - 'API_KEY=2222222222222222222222222222222222222222'
      - 'DJANGO_SECRET_KEY=d8&z=vqy5b#lu0=an1xx9b_7n480af=-gdnqwqvtrs&d6el9=('
      - 'GIT_TAG=0.0.1'
      - 'IMAGE_TAG=0.0.1'
      - 'IMAGE_TITLE=qcon-api'
      - 'ELASTIC_APM_DISABLE_SEND=true'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    hostname: api.local
    networks:
      qcon-network:
        aliases:
          - api.local
    depends_on:
      - postgres
networks:
  qcon-network:
    # external: true
    driver: bridge
    name: qcon-network