version: "3"

services:
  app:
    build: .
    # command: python manage.py runserver 0.0.0.0:8002
    command:
      - ssh-keyscan -t rsa issues.ltc.bcit.ca > ~/.ssh/known_hosts;
    image: qcon-api
    environment:
      - DEBUG=True
    restart: always
    tty: true
    volumes:
      - .:/code
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - "8000:8000"
      - "8002:8002"
      - "8001:8001"
    hostname: api.local
    networks:
      qcon-network:
        aliases:
          - api.local

networks:
  qcon-network:
    # external: true
    driver: bridge
    name: qcon-network