version: "3"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    image: qcon-api
    env_file: .env
    environment:
      - DEBUG="True"
    restart: always
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge