version: "3"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    image: qcon-api
    environment:
      - DEBUG=True
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    hostname: api.local
    networks:
      qcon-network:
        aliases:
          - api.local

networks:
  qcon-network:
    # external: true
    driver: bridge
    name: qcon-network