version: "3"

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    image: qconapi
    environment:
      - DEBUG=True
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - API_KEY=2222222222222222222222222222222222222222
      - DJANGO_SECRET_KEY='d8&z=vqy5b#lu0=an1xx9b_7n480af=-gdnqwqvtrs&d6el9=('
    restart: always
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge