apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: qcon
build:
  artifacts:
  - image: qcon
    context: .
  local:
    push:
    useDockerCLI: true
#    sync:
#      infer:
#      - 'api_v1/*'
deploy:
  kubectl:
    manifests:
#    - namespace.yaml
#    - storage.yaml
    - service.yaml
    - deployment.yaml
    - ingress.yaml