apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: qcon-api
build:
  artifacts:
  - image: qcon-api
    context: .
  local:
    useDockerCLI: true
#    useBuildkit: true
deploy:
  kustomize:
    paths:
    - overlays/dev
# enable with `skaffold dev -p {profile.name}`
profiles:
- name: v
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-v
- name: a
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-a
- name: k
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-k