##### Development Settings (remote cluster deploy validation) #####
#
# 1. Set skaffold config:
#    `skaffold config set default-repo registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api`
#
# 2. Run skaffold:
#    `skaffold dev -p {profile.name}`     eg. skaffold dev -p k
#
# If you run into errors, you may find the following works:
#    `skaffold dev -p {profile.name} --default-repo registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api --status-check=true`
#
# TODO: find a better way to limit network traffic namespacing between identical pod deployments
#
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: qcon-api
build:
  artifacts:
  - image: qcon-api
    context: .
  local:
    useDockerCLI: true
#    useBuildkit: true
deploy:
  kustomize:
    paths:
    - overlays/dev
profiles:
- name: v
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-v
- name: a
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-a
- name: k
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-k