apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: qcon-api
build:
  artifacts:
  - image: qcon-api
    context: .
  local:
#    useDockerCLI: true
    useBuildkit: true
deploy:
  kustomize:
    paths:
    - overlays/dev
#profiles:
#- name: prod
#  deploy:
#    kustomize:
#      paths:
#      - overlays/prod
#- name: staging
#  deploy:
#    kustomize:
#      paths:
#      - overlays/staging
portForward:
  - resourceType: deployment
    resourceName: qcon-api
    address: 0.0.0.0
    port: 300008
    localPort: 8000 # *Optional*