apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qcon-pv-claim
#  namespace: web-apps
  labels:
    app: qcon
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi