apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: qcon-api
  template:
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-credentials
        - name: qcon-api
          envFrom:
            - configMapRef:
                name: elasticapm-config
            - secretRef:
                name: tokens
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: admin-credentials
          env:
            - name: GIT_TAG
              valueFrom:
                configMapKeyRef:
                  name: deploy-vars
                  key: GIT_TAG
