apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: qcon-api
  template:
    spec:
      containers:
        - name: qcon-api
          env:
            - name: GIT_TAG
              valueFrom:
                configMapKeyRef:
                  name: deploy-vars
                  key: GIT_TAG
