apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=qcon-api}

resources:
- ../../base

commonLabels:
  environment: review

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
- name: qcon-api
  newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/qcon/qcon-api}
  newTag: ${IMAGE_TAG:=stable}

patches:
- target:
    kind: Ingress
  path: ingress-patch.yaml
- target:
    kind: Deployment
  path: deployment-patch.yaml

# # Create a .dockerconfig.json. Then uncomment this section for local cluster development.
# #
# - target:
#     kind: Deployment
#   patch: |-
#     - op: add
#       path: /spec/template/spec/imagePullSecrets
#       value: [name: gitlab-registry-credentials]

# # Uncomment for local cluster development
# #
# secretGenerator:
  # - name: gitlab-registry-credentials
  #   type: kubernetes.io/dockerconfigjson
  #   files:
  #     - .dockerconfigjson=secrets/.dockerconfig.json

components:
  - ./vault-secrets
