apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qcon-api
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443"
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-credentials
        - name: qcon-api
          envFrom:
            - configMapRef:
                name: elasticapm-config
            - secretRef:
                name: tokens
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: admin-credentials
