apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: stable
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: qcon-api-
nameSuffix: -stable
# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 2.18.18 # {"$imagepolicy": "qcon:qcon-api-image-policy-stable:tag"}
images:
  - name: "qcon-api"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-api"
    newTag: "2.18.18" # {"$imagepolicy": "qcon:qcon-api-image-policy-stable:tag"}
# Adds elasticapm config and Vault agent annotations to deployment
#
patches:
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-stable/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-stable
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-api-stable
    behavior: merge
