apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qcon
resources:
  - ../../base
commonLabels:
  environment: stable
commonAnnotations:
  version: 2.18.4 # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
images:
  - name: "qcon-api"
    newName: "registry.ltc.bcit.ca/web-apps/qcon/qcon-api"
    newTag: "2.18.4" # {"$imagepolicy": "qcon:qcon-api-image-policy:tag"}
# Adds elasticapm config and Vault agent annotations to deployment
#
patches:
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=qcon-api-stable
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
