apiVersion: apps/v1
kind: Deployment

metadata:
  name: qcon-api
  labels:
    app: qcon-api
spec:
  template:
    metadata:
        labels:
          app: web
        annotations:
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/role: 'web'
          vault.hashicorp.com/agent-inject-secret-config: 'secret/data/web'
          # Environment variable export template
          vault.hashicorp.com/agent-inject-template-config: |
            {{ with secret "secret/data/web" -}}
              export api_key="{{ .api_token }}"
            {{- end }}
    spec:
      containers:
      - name: qcon-api
        image: qcon-api