apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: qcon-api-ingress
spec:
  rules:
  - host: reviews.dev.ltc.bcit.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qcon-api
            port:
              number: 8000