apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: qcon-api-ingress
spec:
  rules:
  - host: reviews-dev-cp.dev.ltc.bcit.ca
    http:
      paths:
# should be: $DEV_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/review/$CI_COMMIT_REF_SLUG
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qcon-api-service
            port:
              number: 8000
