apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qcon-api

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

patches:
  - path: deployment.yaml
    target:
      kind: Deployment