         
metadata:         
  name: qcon-api-ingress         
  namespace          
  annotations:         
    nginx.ingress.kubernetes.io/rewrite-target: /$2         
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite (qcon-api)$ qcon-api/ redirect;         
spec:         
  tls:         
  - hosts:         
    -          
    secretName:          
  rules:         
  - host:          
    http:         
      paths:         
      - path: /qcon-api         
        pathType: Prefix         
        backend:         
          service:         
            name: qcon-api-service         
            port:         
              number: 
