apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qcon

resources:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml

# TODO: add an ingress for staging
# resources:
# - ingress.yaml
