#
# TODO: ImagePullSecret moved to common-defaults repo
#
apiVersion: v1
kind: Secret
metadata:
  name: dependabot-qcon-api
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kZXYubHRjLmJjaXQuY2EiOnsidXNlcm5hbWUiOiJkZXBlbmRhYm90LXFjb24tYXBpIiwicGFzc3dvcmQiOiJONG41c3lvVVJIWUV0djJkdU0yUCIsImVtYWlsIjoiY291cnNlcHJvZHVjdGlvbkBiY2l0LmNhIiwiYXV0aCI6IlpHVndaVzVrWVdKdmRDMXhZMjl1TFdGd2FUcE9ORzQxYzNsdlZWSklXVVYwZGpKa2RVMHlVQT09In19fQ==
type: kubernetes.io/dockerconfigjson