apiVersion: apps/v1
kind: Deployment

metadata:
  name: qcon-api
  labels:
    app: qcon-api
spec:
  selector:
    matchLabels:
      app: qcon-api
  replicas: 1
  template:
    metadata:
      labels:
        app: qcon-api
    spec:
      containers:
      - name: qcon-api
        image: registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api:stable
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - containerPort: 8000
        volumeMounts:
          - mountPath: /code
            name: shared-data
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
        livenessProbe:                  
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
      imagePullSecrets:
        - name: dependabot-qcon-api
      
      serviceAccountName: vault-auth
      volumes:
        - configMap:
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
            name: qcon-api-vault-agent-config
          name: config
        - emptyDir: {}
          name: shared-data
      initContainers:
        - args:
            - agent
            - -config=/etc/vault/vault-agent-config.hcl
            - -log-level=debug
          env:
            - name: VAULT_ADDR
              value: https://vault.ltc.bcit.ca:8200
          image: vault
          name: vault-agent
          volumeMounts:
            - mountPath: /etc/vault
              name: config
            - mountPath: /etc/secrets
              name: shared-data