apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - dependabot-qcon-api.yaml
  - deployment.yaml
  - service.yaml

# TODO: add ingress automatically when DNS delegation complete
# - ingress.yaml