apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# If workloads share a common namespace, set the `namePrefix` in the overlay
#   `kustomization.yaml` to avoid name collisions.
#
# namePrefix: qcon-api-

resources:
  - ./nginx-unprivileged
  - ingress.yaml
  - serviceaccount.yaml

commonLabels:
  app: qcon-api
  app.kubernetes.io/name: qcon-api


# Enables Kustomize to simplify the deployment name
#
patches:
- target:
    kind: Deployment
    labelSelector: "app=nginx"
  path: deployment.yaml
  options:
    allowNameChange: true


configMapGenerator:

# Generates elasticapm config
#
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

# Configure postgres to allow all connections
#
  - name: postgres-config
    literals:
      - POSTGRES_HOST_AUTH_METHOD=trust

# Replaces default nginx config
#
  - name: nginx-config
    files:
      - nginx.conf
    behavior: replace



