apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./nginx-unprivileged
  - ingress.yaml
  - serviceaccount.yaml

# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml

commonLabels:
  app: qcon-api
  app.kubernetes.io/name: qcon-api

# Enables Kustomize to simplify the deployment name
#
patches:
  - target:
      kind: Deployment
      labelSelector: "app=nginx"
    path: deployment.yaml
    options:
      allowNameChange: true

configMapGenerator:
  # Generates elasticapm config
  #
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

  # Configure postgres to allow all connections
  #
  - name: postgres-config
    literals:
      - POSTGRES_HOST_AUTH_METHOD=trust

# Replaces default nginx config
#
components:
  - ../../conf.d
