# This file is for teaching kustomize how to substitute names
#
---
nameReference:

  - kind: HelmRepository
    fieldSpecs:
      - kind: HelmRelease
        path: spec/chart/spec/sourceRef/name

  - kind: VaultStaticSecret
    fieldSpecs:
      - kind: VaultStaticSecret
        path: spec/destination/name
      - kind: HelmRelease
        path: spec/values/config/secretName
