apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcon-api
  labels:
    app: qcon-api
spec:
  template:
    spec:
      containers:
      - name: qcon-api
        image: registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api/qcon-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
  replicas: 1
  strategy:
    type: Recreate