apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# namespace: web-apps
#nameSuffix: -prod

patchesStrategicMerge:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- storage.yaml