apiVersion: v1
kind: PersistentVolume
metadata:
  name: qcon-api-pv-volume
  labels:
    type: local
spec:
  storageClassName: fast
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/code"
---    
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qcon-api-pv-claim
  labels:
    app: qcon-api
spec:
  storageClassName: fast
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi