# Kaniko template

.build-with-kaniko:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - | 
      echo "Building and shipping image to $CI_REGISTRY_IMAGE"
      # Build date for opencontainers
      BUILDDATE="'$(date '+%FT%T%z' | sed -E -n 's/(\+[0-9]{2})([0-9]{2})$/\1:\2/p')'" #rfc 3339 date
      IMAGE_LABELS="$IMAGE_LABELS \
        --label org.opencontainers.image.created=$BUILDDATE \
        --label build-date=$BUILDDATE"
      # Description for opencontainers
      BUILDTITLE=$(echo $CI_PROJECT_TITLE | tr " " "_")
      IMAGE_LABELS="$IMAGE_LABELS \
        --label org.opencontainers.image.title=$BUILDTITLE \
        --label org.opencontainers.image.description=$BUILDTITLE"
      
      # Add extra metadata json format for label
      echo "    { \
        "name": "qcon-api", \
        "cluster_name": $TEAM_TAG \
        "version": { \
            "number": $VERSION, \
            "build_hash": "5529939d0f2...", \
            "build_timestamp": "2021-09-04T03..." \
        }, \  
      }" >> testfile.txt 

      # Build Version Label and Tag from git tag, LastVersionTagInGit was placed by a previous job artifact
      VERSIONLABEL=$CI_COMMIT_TAG
      if [[ ! -z "$VERSIONLABEL" ]]; then 
        IMAGE_LABELS="$IMAGE_LABELS --label org.opencontainers.image.version=$VERSIONLABEL"
        ADDITIONALTAGLIST="$ADDITIONALTAGLIST $VERSIONLABEL"
      fi
      
      ADDITIONALTAGLIST="$ADDITIONALTAGLIST $CI_COMMIT_SHORT_SHA"
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then ADDITIONALTAGLIST="$ADDITIONALTAGLIST latest"; fi
      if [[ "$CI_COMMIT_BRANCH" == "release" ]]; then ADDITIONALTAGLIST="$ADDITIONALTAGLIST stable"; fi
      if [[ -n "$ADDITIONALTAGLIST" ]]; then 
        for TAG in $ADDITIONALTAGLIST; do 
          FORMATTEDTAGLIST="${FORMATTEDTAGLIST} --tag $CI_REGISTRY_IMAGE:$TAG "; 
        done; 
      fi
      
      # Reformat Docker tags to kaniko's --destination argument:
      FORMATTEDTAGLIST=$(echo "${FORMATTEDTAGLIST}" | sed s/\-\-tag/\-\-destination/g) 

      echo "Kaniko arguments to run: \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKO_CACHE_ARGS $FORMATTEDTAGLIST $IMAGE_LABELS"
      mkdir -p /kaniko/.docker
 
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" \
        > /kaniko/.docker/config.json
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile $KANIKO_CACHE_ARGS $FORMATTEDTAGLIST $IMAGE_LABELS \
# --label short_sha=$CI_COMMIT_SHORT_SHA
# --label version=$VERSION

  artifacts:
    paths:
      - testfile.txt