##### Development Settings (remote cluster deploy validation) #####
#
# 1. Set skaffold config:
#    `skaffold config set default-repo registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api`
#
# 2. Run skaffold:
#    `skaffold dev -p {profile.name} --port-forward -f deploy/skaffold.yaml`
#
# 3. Login to image registry:
#     `docker login registry.dev.ltc.bcit.ca`
#
# TODO: find a better way to spin up identical pod deployments (to limit scope for pod network connectivity)
#
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: qcon-api
build:
  tagPolicy:
    gitCommit:
      prefix: dev-
  artifacts:
  - image: qcon-api
    context: ../
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
    - overlays/dev
profiles:
- name: v
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-v
- name: a
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-a
- name: k
  deploy:
    kustomize:
      paths:
      - overlays/dev
      defaultNamespace: default-k