# Build image with Kaniko and push to project registry
.build_image:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    IMAGE_LABELS: >
      --label org.opencontainers.image.version=$VERSION_TAG
      --label org.opencontainers.image.revision=$CI_COMMIT_SHA
      --label org.opencontainers.image.source=$CI_PROJECT_URL
      --label version=$VERSION_TAG
      --label build_hash=$CI_COMMIT_SHA
      --label build_short_sha=$CI_COMMIT_SHORT_SHA
      --label build_timestamp=$BUILD_DATE
      --label build_env=$BUILD_ENV
# --label tagline=$APP_TAGLINE
  script:
    - | 
      echo -e "Building and shipping image to $CI_REGISTRY_IMAGE \
      \nImage Labels being applied: \
      \n \
      \n  org.opencontainers.image.version=$VERSION_TAG \
      \n  org.opencontainers.image.revision=$CI_COMMIT_SHA \
      \n  org.opencontainers.image.source=$CI_PROJECT_URL \
      \n  version=$VERSION_TAG \
      \n  build_hash=$CI_COMMIT_SHA \
      \n  build_short_sha=$CI_COMMIT_SHORT_SHA \
      \n  build_timestamp=$BUILD_DATE \
      \n  build_env=$BUILD_ENV \
      \n"
      
      # Build date will be slightly different from "\$CI_PIPELINE_CREATED_AT"
      BUILD_DATE="'$(date '+%FT%T%z' | sed -E -n 's/(\+[0-9]{2})([0-9]{2})$/\1:\2/p')'" #rfc 3339 date

      IMAGE_LABELS="$IMAGE_LABELS \
        --label org.opencontainers.image.created=$BUILD_DATE"

      BUILD_TITLE=$(echo $CI_PROJECT_TITLE | tr " " "_")

      IMAGE_LABELS="$IMAGE_LABELS \
        --label org.opencontainers.image.title=$BUILD_TITLE"
      
      ADDITIONALTAGLIST="$ADDITIONALTAGLIST $CI_COMMIT_SHORT_SHA"

      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then ADDITIONALTAGLIST="$ADDITIONALTAGLIST latest"; fi

      if [[ "$CI_COMMIT_TAG" ]]; then
        SHORT_TAG=$(echo $CI_COMMIT_TAG | sed 's/v//')
        ADDITIONALTAGLIST="$ADDITIONALTAGLIST $SHORT_TAG stable"; fi

      if [[ -n "$ADDITIONALTAGLIST" ]]; then 
        for TAG in $ADDITIONALTAGLIST; do 
          FORMATTEDTAGLIST="${FORMATTEDTAGLIST} --tag $CI_REGISTRY_IMAGE:$TAG "; 
        done;
      fi
      
      # Reformat Docker tags to kaniko's --destination argument:
      FORMATTEDTAGLIST=$(echo "${FORMATTEDTAGLIST}" | sed s/\-\-tag/\-\-destination/g) 

      mkdir -p /kaniko/.docker
 
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" \
        > /kaniko/.docker/config.json
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $CI_PROJECT_DIR/Dockerfile $FORMATTEDTAGLIST $IMAGE_LABELS