# Creates namespace annotated to ensure it's visible in the Rancher Default project
.create-annotated-namespace:
  script:
    - |
      # Determine environment
      if [ "$CI_ENV" == "dev" ] && [ $TEAM_TAG == "dev-cp" ]
      then
          CLUSTER_ID="$RANCHER_DEV_CP_CLUSTER_ID"
          PROJECT_ID="$RANCHER_DEV_CP_DEFAULT_PROJECT_ID"
          NAMESPACE_NAME="$CI_COMMIT_REF_SLUG"
      elif [ "$CI_ENV" == "dev" ] && [ $TEAM_TAG == "dev-vsm" ]
      then
          CLUSTER_ID="$RANCHER_DEV_VSM_CLUSTER_ID"
          PROJECT_ID="$RANCHER_DEV_VSM_DEFAULT_PROJECT_ID"
          NAMESPACE_NAME="$CI_COMMIT_REF_SLUG"
      elif [ "$CI_ENV" == "staging" ]
      then
          CLUSTER_ID="$RANCHER_STAGING_CLUSTER_ID"
          PROJECT_ID="$RANCHER_STAGING_DEFAULT_PROJECT_ID"
          NAMESPACE_NAME="$CI_PROJECT_NAME"
      elif [ "$CI_ENV" == "prod" ]
      then
          CLUSTER_ID="$RANCHER_PROD_CLUSTER_ID"
          PROJECT_ID="$RANCHER_PROD_DEFAULT_PROJECT_ID"
          NAMESPACE_NAME="$CI_PROJECT_NAME"
      else
          echo "\"$CI_ENV\" is not set correctly"
          exit 1
      fi
      # Reset namespace if "PROD_NAMESPACE" is set
      if [ -n "$PROD_NAMESPACE" ] && ( [ "$CI_ENV" == "staging" ] || [ "$CI_ENV" == "prod" ] )
      then
          NAMESPACE_NAME="$PROD_NAMESPACE"
      fi
      # Create the namespace
      kubectl apply -f - <<EOF
      apiVersion: v1
      kind: Namespace
      metadata:
        name: $NAMESPACE_NAME
        annotations:
          field.cattle.io/projectId: $CLUSTER_ID:$PROJECT_ID
      EOF
      # Add the namespace to kustomization so all other resources are created there
      echo -e " \
        \nnamespace: $NAMESPACE_NAME" >> deploy/overlays/$CI_ENV/kustomization.yaml


# create tls secret for ingress
.create-tls-secret:
  script:
    - |
      # Determine secret name
      if [ "$CI_ENV" == "staging" ]
      then
        TLS_SECRET_NAME="star-dev-ltc-bcit-ca"
      elif [ "$CI_ENV" == "prod" ]
        TLS_SECRET_NAME="star-ltc-bcit-ca"
      else
        echo "\"$CI_ENV\" is not set correctly"
      fi
      echo "$TLS_CRT" > tls.crt
      echo "$TLS_KEY" > tls.key
      # Create secret via Kustomize secretGenerator spec
      echo -e " \
        \nsecretGenerator: \
        \n- name: $TLS_SECRET_NAME \
        \n  files: \
        \n    - "tls.cert" \
        \n    - "tls.key" \
        \n  type: "kubernetes.io/tls" >> deploy/overlays/$CI_ENV/kustomization.yaml