# Subroutines to patch Kustomization overlays for deployment


# add kustomization annotations to pull latest commit image
.kustomize-image:
  script:
    - |
      echo -e " \
        \nimages: \
        \n  - name: $CI_PROJECT_NAME \
        \n    newName: $CI_REGISTRY_IMAGE \
        \n    newTag: $CI_COMMIT_SHORT_SHA" >> deploy/overlays/$CI_ENV/kustomization.yaml


# link deployment to GitLab Environment/Operations dashboards
.annotate-kustomization:
  script:
    - |
      echo -e " \
        \ncommonAnnotations: \
        \n  app.gitlab.com/app: $CI_PROJECT_PATH_SLUG \
        \n  app.gitlab.com/env: $CI_ENVIRONMENT_SLUG" >> deploy/overlays/$CI_ENV/kustomization.yaml


# Replaces existing `ingress.yaml` to be applied to kustomization
# target URL:
  # - https://{CI_PROJECT_NAME}.{TEAM_TAG}.reviews.ltc.bcit.ca/{CI_BRANCH_NAME}
.patch-ingress-dev:
  script:
    - |
      echo -e " \
      \npatches: \
      \n  - patch: |- \
      \n      apiVersion: networking.k8s.io/v1 \
      \n      kind: Ingress \
      \n      metadata: \
      \n        name: $CI_PROJECT_NAME-ingress \
      \n        annotations: \
      \n          nginx.ingress.kubernetes.io/rewrite-target: /$2 \
      \n          nginx.ingress.kubernetes.io/configuration-snippet: rewrite ($CI_COMMIT_REF_SLUG)$ $CI_COMMIT_REF_SLUG/ redirect; \
      \n  - patch: |- \
      \n      - op: add \
      \n        path: /spec/rules/0/host \
      \n        value: $CI_PROJECT_NAME.$TEAM_TAG.$DEV_HOST \
      \n    target: \
      \n      kind: Ingress \
      \n  - patch: |- \
      \n      - op: replace \
      \n        path: /spec/rules/0/http/paths/0/path \
      \n        value: /$CI_COMMIT_REF_SLUG \
      \n    target: \
      \n      kind: Ingress" >> deploy/overlays/$CI_ENV/kustomization.yaml


# STAGING target URL: 
  # - https://latest.dev.ltc.bcit.ca/{CI_PROJECT_NAME}

# PROD target URLs:
  # - https://stable.dev.ltc.bcit.ca/{CI_PROJECT_NAME}
  # - https://{CI_PROJECT_NAME}.ltc.bcit.ca/
.patch-ingress:
  script:
    - |
      if [ "$CI_ENV" == "staging" ]
      then
        CI_HOST="$STAGING_HOST"
      elif [ "$CI_ENV" == "prod" ]
      then
        CI_HOST="$PROD_HOST"
      else
        echo "\"$CI_HOST\" not set correctly"
      fi
      echo -e " \
      \npatches: \
      \n  - patch: |- \
      \n      apiVersion: networking.k8s.io/v1 \
      \n      kind: Ingress \
      \n      metadata: \
      \n        name: $CI_PROJECT_NAME-ingress \
      \n        annotations: \
      \n          nginx.ingress.kubernetes.io/rewrite-target: /$2 \
      \n          nginx.ingress.kubernetes.io/configuration-snippet: rewrite ($CI_PROJECT_NAME)$ $CI_PROJECT_NAME/ redirect; \
      \n      spec: \
      \n        tls: \
      \n        - hosts: \
      \n            - $CI_HOST \
      \n          secretName: $TLS_SECRET_NAME \
      \n  - patch: |- \
      \n      - op: add \
      \n        path: /spec/rules/0/host \
      \n        value: $CI_HOST \
      \n    target: \
      \n      kind: Ingress \
      \n  - patch: |- \
      \n      - op: replace \
      \n        path: /spec/rules/0/http/paths/0/path \
      \n        value: /$CI_PROJECT_NAME \
      \n    target: \
      \n      kind: Ingress" >> deploy/overlays/$CI_ENV/kustomization.yaml
