# Semantic Release template
.semantic_release:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:14-buster-slim
  before_script:
    - |
      apt-get update
      apt-get install -y --no-install-recommends \
        git-core \
        ca-certificates

      GIT_AUTHOR_NAME=$GITLAB_USER_LOGIN
      GIT_AUTHOR_EMAIL=$GITLAB_USER_EMAIL
      GIT_COMMITTER_NAME=$GITLAB_USER_LOGIN
      GIT_COMMITTER_EMAIL=$GITLAB_USER_EMAIL
      
      npm install -g semantic-release @semantic-release/gitlab