apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcon-api
spec:
  selector:
    matchLabels:
      app: qcon-api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: qcon-api
        tier: backend
    spec:
      containers:
      - name: qcon-api
        image: registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api:stable
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: gitlab-reg-creds
