apiVersion: apps/v1
kind: Deployment
metadata:
  name: qcon-api
  labels:
    app: qcon-api
spec:
  selector:
    matchLabels:
      app: qcon-api
  template:
    metadata:
      labels:
        app: qcon-api
    spec:
      containers:
      - name: qcon-api
        image: registry.dev.ltc.bcit.ca/web-apps/qcon/qcon-api
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: qcon-api-persistent-storage
          mountPath: "/code"
      imagePullSecrets:
        - name: gitlab-img-pull
      volumes:
      - name: qcon-api-persistent-storage
        persistentVolumeClaim:
          claimName: qcon-api-pv-claim